### ISSUE TITLE
Could you provide an updated nightly?

### ISSUE THREAD

**Issue by bleuge** [simonowen/samdisk#17]
I want to test PC formats support, and have many GBs to test it, all formats not just ipf/kryo/img formats.
If you want to test some specific format just ask. 
Thanks!

**Comment by bleuge** [comment]
Man, you were fast, thanks! :D 
Downloaded.

**Comment by simonowen** [comment]
:)

I'd like to automate builds at some point, but the releases I build also use vcpkg with extra flags for XP compatibility and to use older CPU instructions for wider compatibility.

**Comment by bleuge** [comment]
I am mainly interested in PC images, I've been coding my own tool for ages, but...

There many obscure formats out there, more or less all of them are documented or supported in some way in other tools, some of them DOS. Also old DOS versions floppies, 1.x and 2.x specifically, I've seen many tools crash on them or just not supporting them, Fat issues, no bpb, strange boots, etc...

What do you think of supporting HD images as a result of supporting Fat12/Fat16 ? I am still looking for a commandline tool able to list/put/extract files from a old DOS hd image. 
This is very very useful for development and automatic testing of many things in emulators as dosbox or 86box. Supporting up to a 2GB or so would be a dream.

Anyway thanks for updating Samdisk, I've used it many times, and excuse my verbosity :D

**Comment by simonowen** [comment]
Most PC protections I've seen haven't been too challenging, but I've probably only seen a few dozen samples. The worst was probably Knightforce, which uses the same KBI-19 protection as the Amstrad CPC version. Most other PC formats seemed to be simple tricks with extra sectors and errors. I don't know if DOSbox and similar programs support disk images containing custom formats, but if you find any that SAMdisk doesn't understand I'll be happy to add them.

SAMdisk doesn't currently deal much with files inside images, except for a few supported directory listings (FAT isn't included yet!). I've mostly been focussed on blindly reading and writing entire images.  The hard disk support is also mostly full image based too.  Floppy copy protections tend to break the rules to fool file-level disk copiers, so working at sector or track level is often the only way to handle them.

Creating FAT-format image from a list of files would be a useful feature, which could be a new sub-command. Modifying existing images can get messy -- treating modifications as a full extraction and rebuild after changes would be easier.

**Comment by bleuge** [comment]
Thanks for considering, I was wrong about already Fat, maybe I was confused with DiscImageChef tool (check it if you haven't).
Yes, afaik, PC protections were not too hard (am I right If I say are on par with Atari St protections?), being C64, and Amiga the most convoluted (the controller was sooo flexible). 
I'll test Samdisk against some thousands images, in all formats it supports (PC) and report If something is weird.
Thanks!

**Comment by simonowen** [comment]
Somehow I completely missed this reply until now -- sorry!

DiscImageChef allows you to manipulate the contents of images, which SAMdisk doesn't support at all.  SAMdisk specialises in non-standard and protected disks, so it should still have the edge for reading and writing full images.

PC protections are closest to Amstrad CPC and Spectrum +3 protections, as they use the same floppy disk controller chip. The Atari ST has some challenging protections, as it uses a more flexible WD17xx floppy disk controller that can check the disk in more detail. The Amiga doesn't really have a traditional floppy controller, and just slurps the raw tracks, so its protections can be even more challenging. Even C64 is quite different, as it uses GCR encoding and zoned tracks with different densities. Writing IPF images is recommended, where available, to give the best quality disk for use on original hardware.

**Comment by bleuge** [comment]
Thanks for information!
