### ISSUE TITLE
Copying a disk with '-d' option enabled copies every fourth track to destination image

### ISSUE THREAD

**Issue by shattered** [simonowen/samdisk#5]
How to demo:

- convert raw image to EDSK (I've used a 1228800 byte file filled with random data).   

samdisk convert test.raw test.dsk

- scan the result and observe 80 valid tracks

80 Cyls 2 Heads:
500Kbps MFM, 15 sectors,  512 bytes/sector, gap3=80:
  0.0  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
  1.0  15 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  2.0  14 15 1 2 3 4 5 6 7 8 9 10 11 12 13
  3.0  13 14 15 1 2 3 4 5 6 7 8 9 10 11 12
<...>

- copy EDSK using '-d' option

samdisk copy test.dsk test-d.dsk -d

- scan the result and observe 20 valid tracks (40 were expected)

40 Cyls 2 Heads:
500Kbps MFM, 15 sectors,  512 bytes/sector, gap3=80:
  0.0  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
500Kbps MFM, 15 sectors,  512 bytes/sector, c=4, gap3=80:
  1.0  12 13 14 15 1 2 3 4 5 6 7 8 9 10 11
500Kbps MFM, 15 sectors,  512 bytes/sector, c=8, gap3=80:
  2.0  8 9 10 11 12 13 14 15 1 2 3 4 5 6 7
<...>

**Comment by simonowen** [comment]
This seems to be double-stepping the input and output, which isn't what v3 used to do.  It might still make sense to split the options to give independent control of each.  I'll experiment :)

**Comment by shattered** [comment]
Also, if EDSK is produced from SCP image and not from raw, "copy -d" triggers assertion failure: 

include/Header.h:40: CylHead::CylHead(int, int): Assertion `cyl >= 0 && cyl < MAX_DISK_CYLS' failed.

**Comment by simonowen** [comment]
I hope this is now resolved by b2d921a872c495a9fc90a50bf23880f1fe0815ec.

**Comment by shattered** [comment]
It is.  Thanks!

**Comment by simonowen** [comment]
Thanks for confirming :)
